{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saltedge.authenticator",
    "module": "sdk_v2",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.4.1.aar",
          "url": "sdk_v2-2.4.1.aar",
          "size": 122076,
          "sha512": "f48a590b8236c14943ddffe2af543dfdc8a7918827b9f44a9d236e180db4edc2338ac20957bbe41af71fb335670fcd42092ef359ec70a96728a22090c9e1fb00",
          "sha256": "a65e5ee6bb69584b963dc9473d98c04d5a4cfa89390d8ef7f46025dfe7faa4a3",
          "sha1": "be0409e639619c1de54e97e2eb0d933fd2b02837",
          "md5": "533d79cf0cfa275cde8e6359b691093b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.saltedge.authenticator",
          "module": "sdk_core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_v2-2.4.1.aar",
          "url": "sdk_v2-2.4.1.aar",
          "size": 122076,
          "sha512": "f48a590b8236c14943ddffe2af543dfdc8a7918827b9f44a9d236e180db4edc2338ac20957bbe41af71fb335670fcd42092ef359ec70a96728a22090c9e1fb00",
          "sha256": "a65e5ee6bb69584b963dc9473d98c04d5a4cfa89390d8ef7f46025dfe7faa4a3",
          "sha1": "be0409e639619c1de54e97e2eb0d933fd2b02837",
          "md5": "533d79cf0cfa275cde8e6359b691093b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.4.1-sources.jar",
          "url": "sdk_v2-2.4.1-sources.jar",
          "size": 40062,
          "sha512": "cf2a542d82ce335e68c7e3e43ebfef6c26ff6aa476c1db65b069be5ab3921a16d574d64ed4d995577d21705b98f0bd0f3cfc41b683aa37bc291a7f33f196f330",
          "sha256": "808cc53de131a7aa19fc31b62313821674254c84031e07fb7146ef52796100dc",
          "sha1": "9535ba921bb8a13efdcbbfa8cdc500a7deb2a080",
          "md5": "f84fff5f791ef64f22e678835e1bc4ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk_v2-2.4.1-javadoc.jar",
          "url": "sdk_v2-2.4.1-javadoc.jar",
          "size": 520062,
          "sha512": "0b3e14108cd84cc53c59c0ded55c1671da859ba4a06d9579a09fede4b6d70bcbb4e9117b56b179b38f7e903ec79f94889227a488df16250a1a625daacbcf6f9d",
          "sha256": "38a522fd2196c137d91b9216c30d1024ddd60b7ac67d595bf246fedc7a075d43",
          "sha1": "0f21b2e48d8b22741b9689b490501d0693494104",
          "md5": "caa5927d9b036573be0bc07331df8026"
        }
      ]
    }
  ]
}
